import type { Metadata } from "next";
import { Navbar } from "../src/components/ui/navbar";
import HeadComponent from "./head";
import { WhatsAppFAB } from "../src/components/ui/whatsapp-fab";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`dark ${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <HeadComponent />
      <body className="min-h-full flex flex-col">
        <Navbar />
        {children}
        <WhatsAppFAB />
      </body>
    </html>
  );
}
